// src/components/ui/FontAwesomeIcon.jsx
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { 
  faMobileAlt, 
  faLaptop, 
  faTv, 
  faGamepad, 
  faHeadphones, 
  faClock,
  faCamera,
  faMusic,
  faWifi,
  faHdd,
  faHome,
  faPlane, // Better alternative for drones - represents flying/aerial devices
  faCreditCard,
  faUser,
  faHistory,
  faStar,
  faStarHalfAlt,
  faShoppingCart,
  faHeart,
  faBell,
  faCog,
  faSignOutAlt,
  faMapMarkerAlt,
  faPhone,
  faEnvelope,
  faLock,
  faUnlock,
  faEdit,
  faTrash,
  faPlus,
  faMinus,
  faSearch,
  faFilter,
  faSort,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faTimes,
  faCheck,
  faExclamationTriangle,
  faInfoCircle,
  faShoppingBag,
  faTruck,
  faBox,
  faGift,
  faTicketAlt,
  faMoneyBill,
  faCoins,
  faChartLine,
  faUsers,
  faStore,
  faTag,
  faPercent,
  faBullhorn,
  faAward,
  faMedal,
  faCrown,
  faShieldAlt,
  faSync,
  faRedo,
  faUndo,
  faDownload,
  faUpload,
  faPrint,
  faShare,
  faLink,
  faBookmark,
  faCalendar,
  faComments,
  faQuestionCircle,
  faLifeRing,
  faGlobe,
  faLanguage,
  faMoon,
  faSun,
  faPalette,
  faSlidersH
} from '@fortawesome/free-solid-svg-icons';

// Authentic brand icons
import {
  faCcVisa,
  faCcMastercard,
  faCcPaypal,
  faCcApplePay,
  faGooglePay
} from '@fortawesome/free-brands-svg-icons';


const iconMap = {
  'fa-mobile-alt': faMobileAlt,
  'fa-laptop': faLaptop,
  'fa-tv': faTv,
  'fa-gamepad': faGamepad,
  'fa-headphones': faHeadphones,
  'fa-clock': faClock,
  'fa-camera': faCamera,
  'fa-music': faMusic,
  'fa-wifi': faWifi,
  'fa-hdd': faHdd,
  'fa-home': faHome,
  'fa-drone': faPlane, // Using plane for aerial/flying devices
  // Authentic brand payment icons
  'fa-cc-visa': faCcVisa,
  'fa-cc-mastercard': faCcMastercard,
  'fa-cc-paypal': faCcPaypal,
  'fa-cc-apple-pay': faCcApplePay,
  'fa-google-pay': faGooglePay,
  'fa-user': faUser,
  'fa-history': faHistory,
  'fa-credit-card': faCreditCard,
  'fa-star': faStar,
  'fa-star-half-alt': faStarHalfAlt,
  'fa-star-regular': faStar, // Using solid star for consistency
  'fa-shopping-cart': faShoppingCart,
  'fa-heart': faHeart,
  'fa-bell': faBell,
  'fa-cog': faCog,
  'fa-sign-out-alt': faSignOutAlt,
  'fa-map-marker-alt': faMapMarkerAlt,
  'fa-phone': faPhone,
  'fa-envelope': faEnvelope,
  'fa-lock': faLock,
  'fa-unlock': faUnlock,
  'fa-edit': faEdit,
  'fa-trash': faTrash,
  'fa-plus': faPlus,
  'fa-minus': faMinus,
  'fa-search': faSearch,
  'fa-filter': faFilter,
  'fa-sort': faSort,
  'fa-chevron-down': faChevronDown,
  'fa-chevron-up': faChevronUp,
  'fa-chevron-left': faChevronLeft,
  'fa-chevron-right': faChevronRight,
  'fa-times': faTimes,
  'fa-check': faCheck,
  'fa-exclamation-triangle': faExclamationTriangle,
  'fa-info-circle': faInfoCircle,
  'fa-shopping-bag': faShoppingBag,
  'fa-truck': faTruck,
  'fa-box': faBox,
  'fa-gift': faGift,
  'fa-ticket-alt': faTicketAlt,
  'fa-money-bill': faMoneyBill,
  'fa-coins': faCoins,
  'fa-chart-line': faChartLine,
  'fa-users': faUsers,
  'fa-store': faStore,
  'fa-tag': faTag,
  'fa-percent': faPercent,
  'fa-bullhorn': faBullhorn,
  'fa-award': faAward,
  'fa-medal': faMedal,
  'fa-crown': faCrown,
  'fa-shield-alt': faShieldAlt,
  'fa-sync': faSync,
  'fa-redo': faRedo,
  'fa-undo': faUndo,
  'fa-download': faDownload,
  'fa-upload': faUpload,
  'fa-print': faPrint,
  'fa-share': faShare,
  'fa-link': faLink,
  'fa-bookmark': faBookmark,
  'fa-calendar': faCalendar,
  'fa-comments': faComments,
  'fa-question-circle': faQuestionCircle,
  'fa-life-ring': faLifeRing,
  'fa-globe': faGlobe,
  'fa-language': faLanguage,
  'fa-moon': faMoon,
  'fa-sun': faSun,
  'fa-palette': faPalette,
  'fa-sliders-h': faSlidersH
};

const CustomIcon = ({ icon, className = '', ...props }) => {
  const iconDefinition = iconMap[icon];
  
  if (!iconDefinition) {
    console.warn(`Icon "${icon}" not found`);
    return <span className={`inline-block w-4 h-4 ${className}`}>❓</span>; // Fallback icon
  }

  return <FontAwesomeIcon icon={iconDefinition} className={className} {...props} />;
};

export default CustomIcon;